shared:
    image: node:12

jobs:
    main:
        requires: [~commit]
        steps:
              - hello: echo hi
#             - generate-artifacts:  find ./artifacts -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'
#             - copy-to-artifacts-dir: echo $SD_ARTIFACTS_DIR && cp -r ./artifacts $SD_ARTIFACTS_DIR
    prjob:
        requires: [~pr]
        steps:
            - hello: echo hi
    test:
        requires: [main]
        steps:
            - hello: echo hii
    end:
        requires: [test]
        steps:
            - hello: echo hi
